spring:
  datasource:
    url: jdbc:h2:mem:inventory_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
    generate-unique-name: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
jwt:
  secret: mySecretKey1234567890
  expiration: 3600000